name: 'Execução testes web'

on:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ['ubuntu-latest']

    steps:
      - uses: actions/checkout@v4

      - name: Instalando dependencias
        run: npm install

      - name: Instalando Cypress
        run: npx cypress install

      - name: Testes E2E (end-to-end)
        run: npx cypress run