name: 'Execução testes web'

on:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalando dependencias
        run: npm install

      - name: Instalando Cypress
        run: npm install cypress --save-dev

      - name: Testes E2E (end-to-end)
        run: npx cypress run

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: mochawesome-report
          path: cypress/results/

      